/**
 * Shows how to use tcUnicodeHelper with U8G2 library. TcUnicode library can render both AdafruitGFX and tcUnicode
 * fonts. The text passed to it is normally in UTF-8 format (modern C++ standard).
 *
 * The Unicode fonts are of type TcUnicode and can be generated by TcMenuDesigner: https://github.com/TcMenu/tcMenu/releases
 *
 * This works by providing a `FontHandler` that is responsible for drawing onto your display, taking over the task
 * of drawing characters from the graphics library.
 */

#include <HardwareSerial.h>
#include <SPI.h>
#include <Wire.h>
#include <U8g2lib.h>
#include "Fonts/OpenSansRegular7pt.h"
#include "tcUnicodeU8G2.h"

// For U8G2 based displays, simply create the display as usual, and then create a pipeline and handler.
U8G2_SH1106_128X64_NONAME_F_SW_I2C u8g2(U8G2_R0, 5, 4, U8X8_PIN_NONE);
U8g2TextPlotPipeline u8g2Pipeline(&u8g2);
UnicodeFontHandler fontHandler(&u8g2Pipeline, ENCMODE_UTF8);

void setup() {
    u8g2.begin();
    int baseline;
    fontHandler.setFont(OpenSansRegular7pt);
    Coord textSize = fontHandler.textExtents("Abcdef", &baseline);
    int yFontHeight = (int)textSize.y - baseline;
    Serial.print("Font height is "); Serial.println(yFontHeight);

    fontHandler.setDrawColor(1);
    fontHandler.setFont(OpenSansRegular7pt);
    fontHandler.setCursor(Coord(0, 10));
    fontHandler.print("Hello world");
    u8g2.sendBuffer();
}

void loop() {
    delay(1000);

    u8g2.setColorIndex(0);
    u8g2.drawBox(0, 10, 100, 20);

    fontHandler.setDrawColor(1);
    fontHandler.setFont(OpenSansRegular7pt);
    fontHandler.setCursor(Coord(0, 20));
    fontHandler.print(millis() / 1000);
    u8g2.sendBuffer();
}