/**
 * Shows how to use tcUnicodeHelper with TFT_eSPI library. TcUnicode library can render both AdafruitGFX and tcUnicode
 * fonts. The text passed to it is normally in UTF-8 format (modern C++ standard).
 *
 * The Unicode fonts are of type TcUnicode and can be generated by TcMenuDesigner: https://github.com/TcMenu/tcMenu/releases
 *
 * This works by providing a `FontHandler` that is responsible for drawing onto your display, taking over the task
 * of drawing characters from the graphics library.
 *
 * With TFT_eSPI you'll need to configure the display that you want to use yourself first, and then compile and upload
 * this sketch. Probably best to try and upload an example from the library first.
 */

// before including the graphics library, always include GFXfont from our code. TFTeSPI has an incompatible
// version of the include.
#include "UnicodeFontDefs.h"

// Include the graphics library
#include <TFT_eSPI.h>
// and then include an Adafruit font, and a tcUnicode font
#include <Fonts/RobotoMedium18.h>
#include "Fonts/OpenSansCyrillicLatin18.h"
// and lastly the fontHandler
#include "tcUnicodeTFT_eSPI.h"

//
// For TFTeSPI, we simply create our graphics component `tft` and then we create a `tftPipeline` that draws
// text onto it. Lastly, we create the `fontHandler` that we use to draw Unicode text onto the display.
//
TFT_eSPI tft;
TftSpiTextPlotPipeline tftPipeline(&tft);
UnicodeFontHandler fontHandler(&tftPipeline, ENCMODE_UTF8);

// some text to print
const char* helloText = "Hello World!";

void setup() {
    SPI.begin();
    Serial.begin(115200);

    tft.begin();
	tft.fillScreen(ILI9341_BLACK);

    //
    // Now get the size of the Adafruit_GFX font that we are using, same as above basically.
    //
    int baselineAda;
    fontHandler.setFont(&RobotoMedium18);
    Coord textSize = fontHandler.textExtents(helloText, &baselineAda);
    int yAdaFontHeight = (int)textSize.y - baselineAda;

    Serial.print("Adafruit font height: "); Serial.println(yAdaFontHeight);
    Serial.print("Text size: "); Serial.print(textSize.x); Serial.print(", "); Serial.println(textSize.y);

    fontHandler.setDrawColor(ILI9341_YELLOW);
    fontHandler.setFont(&RobotoMedium18);
    fontHandler.setCursor(Coord((tft.width() - textSize.x) / 2, yAdaFontHeight + 10));
    fontHandler.print(helloText);

    Serial.print("Writing text at "); Serial.print((tft.width() - textSize.x) / 2); Serial.print(",");
    Serial.println(yAdaFontHeight + 10);

}

void loop() {
    delay(1000);

    tft.fillRect(0, 80, tft.width(), 30, ILI9341_BLACK);
    fontHandler.setDrawColor(ILI9341_WHITE);
    fontHandler.setFont(OpenSansCyrillicLatin18);
    fontHandler.setCursor(Coord(0, 100));
    fontHandler.print(millis() / 1000);
}


